-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2021-06-21 15:13:30 CEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE igrac (
    idi              INTEGER NOT NULL,
    ime              VARCHAR2(100 CHAR) NOT NULL,
    prezime          VARCHAR2(50 CHAR) NOT NULL,
    datum_rodjenja   DATE NOT NULL,
    mesto            VARCHAR2(100 CHAR) NOT NULL,
    klub_idk         INTEGER NOT NULL
);

ALTER TABLE igrac ADD CONSTRAINT igrac_pk PRIMARY KEY ( idi );

CREATE TABLE klub (
    mesto   VARCHAR2(100 CHAR) NOT NULL,
    idk     INTEGER NOT NULL,
    ime     VARCHAR2(100 CHAR) NOT NULL
);

ALTER TABLE klub ADD CONSTRAINT klub_pk PRIMARY KEY ( idk );

CREATE TABLE sudi (
    utakmica_sifra   VARCHAR2(30 CHAR) NOT NULL,
    sudija_ids       INTEGER NOT NULL
);

ALTER TABLE sudi ADD CONSTRAINT zs64020_sudi_pk PRIMARY KEY ( utakmica_sifra,
                                                              sudija_ids );

CREATE TABLE sudija (
    ids       INTEGER NOT NULL,
    ime       VARCHAR2(100 CHAR) NOT NULL,
    prezime   VARCHAR2(100 CHAR) NOT NULL,
    plata     INTEGER
);

ALTER TABLE sudija ADD CONSTRAINT sudija_pk PRIMARY KEY ( ids );

CREATE TABLE utakmica (
    sifra         VARCHAR2(30 CHAR) NOT NULL,
    datumivreme   DATE NOT NULL,
    domacin       INTEGER NOT NULL,
    gost          INTEGER NOT NULL,
    klub_idk      INTEGER NOT NULL,
    klub_idk1     INTEGER NOT NULL
);

ALTER TABLE utakmica ADD CONSTRAINT utakmica_pk PRIMARY KEY ( sifra );

ALTER TABLE igrac
    ADD CONSTRAINT igrac_klub_fk FOREIGN KEY ( klub_idk )
        REFERENCES klub ( idk );

ALTER TABLE utakmica
    ADD CONSTRAINT utakmica_klub_fk FOREIGN KEY ( klub_idk1 )
        REFERENCES klub ( idk );

ALTER TABLE utakmica
    ADD CONSTRAINT utakmica_klub_fkv1 FOREIGN KEY ( klub_idk )
        REFERENCES klub ( idk );

ALTER TABLE sudi
    ADD CONSTRAINT zs64020_sudi_sudija_fk FOREIGN KEY ( sudija_ids )
        REFERENCES sudija ( ids );

ALTER TABLE sudi
    ADD CONSTRAINT zs64020_sudi_utakmica_fk FOREIGN KEY ( utakmica_sifra )
        REFERENCES utakmica ( sifra );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

insert into zs64020_klub (idk, ime, mesto)
values (1, 'KK Mestiste', 'Mestiste');

insert into zs64020_igrac (idi, klub_idk, ime, prezime, mesto, datum_rodjenja)
values (1, 1, 'Neki', 'Covek', 'Mestiste', '2-Jan-1992');

insert into zs64020_utakmica (sifra, datumivreme, domacin, gost, klub_idk, klub_idk1)
values ('1', '02-Jan-2002', 3, 3, 1, 1);

insert into zs64020_sudija (ids, ime, prezime)
values (1, 'Vlastimir', 'Vlastimirovic');

select distinct *
from zs64020_klub
where idk in (select distinct klub_idk1
                from zs64020_utakmica
                where gost > domacin
);



update sudija s
set s.plata = s.plata * 110 / 100
where 2 >= (select count(su.Utakmica_SIFRA)
            from sudi su
            where su.Sudija_IDS = s.IDS
);


delete
from zs64020_klub
where Mesto = 'Mestiste';